# Application Name
spring.application.name=event-gateway

# Server Port
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:eventdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{traceId}] %logger{36} - %msg%n

# Resilience4j Circuit Breaker
resilience4j.circuitbreaker.instances.accountService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.accountService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.accountService.sliding-window-size=5
resilience4j.circuitbreaker.instances.accountService.wait-duration-in-open-state=10s

# Resilience4j Retry
resilience4j.retry.instances.accountService.max-attempts=3
resilience4j.retry.instances.accountService.wait-duration=1s

# Resilience4j Time Limiter
resilience4j.timelimiter.instances.accountService.timeout-duration=2s